### ISSUE TITLE
userData don't yet exists when onUserFormSave is invoked?

### ISSUE THREAD

**Issue by whitebyte** [BobRay/ClassExtender#3]
Hello, Bob. I have a strange issue with my ClassExtended user profile. I have a plugin that fires on onUserFormSave event. According to RTFM, the user object should already exist, but _sometimes_ when i trying to access user's data object, i recieve null

``` php
$data = $modx->getObject('userData', array('userdata_id' => $id));

if (is_null($data)) {
        $modx->log(modX::LOG_LEVEL_ERROR, 'data is null');
}
```

Usually $data is null, _sometimes_ is an object. Is this sort of a race condition? 
I've tried a dirty hack:

``` php
if (is_null($data)) {
        $modx->log(modX::LOG_LEVEL_ERROR, 'data is null');
        sleep(3);
        $data = $modx->getObject('userData', array('userdata_id' => $id));

        if (is_null($data)) {
            $modx->log(modX::LOG_LEVEL_ERROR, 'data is still null, aborting');
            return false;
        }
    }
```

in some rare cases this code gives object, not null. I don't understand it at all.

**Comment by BobRay** [comment]
I'm afraid I don't know what could cause that. I don't think it could be a race condition because you're only asking for one object. 

Are you sure that $id is set and correct?

You might try adding false as a third argument to getObject(). I think that will force getting the object from the DB rather than the cache.

**Comment by whitebyte** [comment]
After some investigation i've found that it was envinroment-specific bug, not related to the extra itself.Thank you for this really useful piece of software!

**Comment by BobRay** [comment]
You're welcome!
